### ISSUE TITLE
platform is linux

### ISSUE THREAD

**Issue by neticeydh** [mbello/memory-tempfile#2]
Hi
      I get a issue with the platform return with Linux-xxxx.
          print(platform.platform())
          Linux-3.10.0-862.9.1.el7.x86_64-x86_64-with-centos-7.5.1804-Core

**Comment by hughjward** [comment]
@neticeydh I have created a fork with a simple fix for this!

**Comment by mbello** [comment]
Thanks for the report, it's fixed now and will be avaliable on pypi as version 2.2.0.

**Comment by mbello** [comment]
Closed with release 2.2.0
