### ISSUE TITLE
Does this support writing by one script and reading by another script?

### ISSUE THREAD

**Issue by AlexLuya** [mbello/memory-tempfile#4]
I tried,but seems like:no,is it possible to support it?

**Comment by mbello** [comment]
Can you give me more details of your use case and what you actually tried that failed?

It should work because you get a standard file, the only "special thing" is that such file will be on a memory-based filesystem but works exactly the same as a regular file.

In other words, if your case works by writing to /tmp it should work when using this package.

But I am happy to hear more from you to understand your use case and, if feasible, add the necessary bits to support it.

**Comment by AlexLuya** [comment]
@mbello Thanks,I want to use Script_A.py to write a string to a file like this:
----------------------------Scripty_A.py-------------------------------------------------
```
from memory_tempfile import MemoryTempfile
import time

tempfile = MemoryTempfile(preferred_paths = ['/run/user/{uid}'], remove_paths = ['/dev/shm', '/run/shm'],
                          additional_paths = ['/var/run'], filesystem_types = ['tmpfs'], fallback = True)
i = 0
while True:
    time.sleep(1)
    with tempfile.NamedTemporaryFile() as ntf:
            ntf.write(str.encode("This is line %d\r\n" % (i + 1)))
            print(f'{i}th string wrote')
            i += 1
```
At same time,using Script_B.py to read out the content of same file like this:
---------------------------------Script_B.py---------------------------------------------------
```
from memory_tempfile import MemoryTempfile

# By the way, all paths with string {uid} will have it replaced with the user id
tempfile = MemoryTempfile(preferred_paths = ['/run/user/{uid}'], remove_paths = ['/dev/shm', '/run/shm'],
                          additional_paths = ['/var/run'], filesystem_types = ['tmpfs'], fallback = True)

i = 0
while True:
    with tempfile.NamedTemporaryFile() as ntf:
        print(f'{i}th read get: ', ntf.read().decode())
```

But Scripty_B.py keep printing:
```
   1th read get: 
   2th read get: 
  .....
```
The content written by Scripty_A.py can't be read out by Script_B.py

**Comment by mbello** [comment]
@AlexLuya Each script is getting their own tempfile when calling tempfile.NamedTemporaryFIle(). There is logic built into tempfile exactly to avoid name collision, that is, everytime you call that NamedTemporaryFile() function you are guaranteed to get a new file with a name that did not previously exist on the corresponding directory. 

In your case, you would need to find a way for script A to tell Script B the name of the file it is writing to.

**Comment by mbello** [comment]
I am closing this issue as I do not see how the software is at fault here. But we can continue this thread if you have other related questions.

**Comment by AlexLuya** [comment]
@mbello how to tell both script to use this file:/x/y/file_name,I tried:
`preferred_paths = ['/run/user/temp']`
in both script,but not work as expected,by the way,the doc
`https://pypi.org/project/memory-tempfile/2.2.3/`
 is quite technical with many os file management level details,seems like not for user but for developer.

**Comment by frankier** [comment]
This is a software library, so it is made for developers.

It's not clear what your use case is but you could try either creating a ramdisk manually https://www.jamescoyle.net/how-to/943-create-a-ram-disk-in-linux or perhaps using a pipe would be sufficient?

**Comment by AlexLuya** [comment]
@frankier Thanks,my usecase is the a Deep Learning training process will write some realtime info to somewhere ,at the same time, a flask process  may read from this 'somewhere' to show content on a web UI timely,and I could use redis as this 'somewhere',but it is too heavy for this simple task,so want to find a light way to  do it

**Comment by frankier** [comment]
I recommend 0mq for a lightweight message queue alternative, which seems to be what you're describing https://zeromq.org/

A named pipe might also suffice, but 0mq is a lightweight nice abstraction so it's probably best to just use that.
